#include "codane/graph.hpp"
#include <fstream>
#include <set>
namespace codane {
void Graph::validate() const {
 if(nodes.size()>limits.max_graph_nodes) throw std::runtime_error("graph node limit exceeded");
 for(auto const& [id,n]:nodes){std::set<NodeId> u;for(auto const& d:n.depends){if(!u.insert(d).second)throw std::runtime_error("duplicate dependency: "+d);if(!nodes.count(d))throw std::runtime_error("missing dependency: "+d);}for(auto const& a:n.artifact_inputs){if(!nodes.count(a.producer))throw std::runtime_error("missing artifact producer: "+a.producer);if(std::find(n.depends.begin(),n.depends.end(),a.producer)==n.depends.end())throw std::runtime_error("artifact producer is not a dependency: "+a.producer);}}
 std::map<NodeId,int> mark;std::map<NodeId,size_t> memo;std::function<size_t(const NodeId&)> dfs=[&](const NodeId& x){if(mark[x]==1)throw std::runtime_error("graph cycle detected");if(mark[x]==2)return memo[x];mark[x]=1;size_t depth=0;for(auto const& d:nodes.at(x).depends)depth=std::max(depth,dfs(d)+1);mark[x]=2;memo[x]=depth;if(depth>limits.max_graph_depth)throw std::runtime_error("graph depth limit exceeded");return depth;};for(auto const& [id,n]:nodes)dfs(id);
}
std::vector<NodeId> Graph::ready() const{std::vector<NodeId> r;for(auto const&[id,n]:nodes)if(n.state==NodeState::Pending&&n.retry_pending<=0){bool ok=true;for(auto const&d:n.depends)if(nodes.at(d).state!=NodeState::Succeeded)ok=false;if(ok)r.push_back(id);}return r;}
void Graph::mutate(const std::vector<Node>& additions){Graph copy=*this;for(auto n:additions){if(copy.nodes.count(n.id))throw std::runtime_error("duplicate node id: "+n.id);copy.nodes.emplace(n.id,std::move(n));}copy.validate();nodes.swap(copy.nodes);}
static Json strings(const std::vector<std::string>&a){Json::array x;for(auto&s:a)x.emplace_back(s);return x;}static std::vector<std::string> get_strings(const Json&j){std::vector<std::string>x;for(auto&v:j.arr())x.push_back(v.str());return x;}
static Json inputs_json(const std::vector<ArtifactInput>&a){Json::array x;for(auto const&i:a)x.push_back(Json::object{{"from",i.producer},{"path",i.path}});return x;}
static std::vector<ArtifactInput> get_inputs(const Json&j){std::vector<ArtifactInput>x;for(auto const&v:j.arr()){if(v.is_object())x.push_back({v.at("from").str(),v.at("path").str(),{}});else x.push_back({"",v.str(),{}});}return x;}
Json graph_json(const Graph&g){Json::array ns;for(auto const&[id,n]:g.nodes){Json::object o{{"id",n.id},{"type",n.type},{"prompt",n.prompt},{"depends_on",strings(n.depends)},{"command",strings(n.command)},{"state",state_name(n.state)},{"attempts",n.attempts},{"retry_pending",n.retry_pending},{"loop_iteration",n.loop_iteration},{"verified",n.verified},{"accepted",n.accepted},{"artifacts",strings(n.artifacts)},{"artifact_inputs",inputs_json(n.artifact_inputs)}};if(n.verifier)o["verify"]=*n.verifier;ns.push_back(o);}return Json::object{{"name",g.name},{"max_parallel",(double)g.limits.max_parallel},{"max_graph_nodes",(double)g.limits.max_graph_nodes},{"max_graph_depth",(double)g.limits.max_graph_depth},{"max_attempts",g.retry.max_attempts},{"backoff_ms",(double)g.retry.backoff.count()},{"backoff_multiplier",g.retry.multiplier},{"nodes",ns}};}
Graph graph_from_json(const Json&j){Graph g;g.name=j.has("name")?j.at("name").str():"graph";if(j.has("max_parallel"))g.limits.max_parallel=(size_t)j.at("max_parallel").number();if(j.has("max_graph_nodes"))g.limits.max_graph_nodes=(size_t)j.at("max_graph_nodes").number();if(j.has("max_graph_depth"))g.limits.max_graph_depth=(size_t)j.at("max_graph_depth").number();if(j.has("max_attempts"))g.retry.max_attempts=(int)j.at("max_attempts").number();if(j.has("backoff_ms"))g.retry.backoff=std::chrono::milliseconds((int)j.at("backoff_ms").number());if(j.has("backoff_multiplier"))g.retry.multiplier=j.at("backoff_multiplier").number();for(auto&x:j.at("nodes").arr()){Node n;n.id=x.at("id").str();n.type=x.has("type")?x.at("type").str():"agent";n.prompt=x.has("prompt")?x.at("prompt").str():"";if(x.has("depends_on"))n.depends=get_strings(x.at("depends_on"));if(x.has("command"))n.command=get_strings(x.at("command"));if(x.has("state"))n.state=parse_state(x.at("state").str());if(x.has("attempts"))n.attempts=(int)x.at("attempts").number();if(x.has("retry_pending"))n.retry_pending=(int)x.at("retry_pending").number();if(x.has("loop_iteration"))n.loop_iteration=(int)x.at("loop_iteration").number();if(x.has("verified"))n.verified=x.at("verified").boolean();if(x.has("accepted"))n.accepted=x.at("accepted").boolean();if(x.has("artifacts"))for(auto const&a:x.at("artifacts").arr()){if(a.is_object())n.artifact_inputs.push_back({a.at("from").str(),a.at("path").str(),{}});else n.artifacts.push_back(a.str());}if(x.has("artifact_inputs"))n.artifact_inputs=get_inputs(x.at("artifact_inputs"));if(x.has("verify"))n.verifier=x.at("verify");g.nodes.emplace(n.id,std::move(n));}g.validate();return g;}
std::filesystem::path artifact_path(const std::filesystem::path&root,const NodeId&node,const std::string&name){if(node.empty()||node=="."||node==".."||node.find('/')!=std::string::npos||name.empty()||std::filesystem::path(name).is_absolute())throw std::runtime_error("artifact path escapes run root");for(auto const&part:std::filesystem::path(name))if(part=="..")throw std::runtime_error("artifact path escapes run root");auto base=std::filesystem::weakly_canonical(root/"artifacts"/node);auto out=std::filesystem::weakly_canonical(base/std::filesystem::path(name));auto prefix=base.string()+std::string(1,std::filesystem::path::preferred_separator);if(out.string().rfind(prefix,0)!=0)throw std::runtime_error("artifact path escapes run root");return out;}
void populate_artifacts(AgentRequest&q,const Node&n,const std::filesystem::path&root){q.artifacts.clear();for(auto const&i:n.artifact_inputs){if(i.producer.empty())throw std::runtime_error("artifact input missing producer");auto path=artifact_path(root,i.producer,i.path);if(!std::filesystem::is_regular_file(path))throw std::runtime_error("missing artifact: "+i.producer+"/"+i.path);q.artifacts.push_back({i.producer,i.path,path.string()});}}
Graph load_graph(const std::filesystem::path&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot read graph");std::string s((std::istreambuf_iterator<char>(f)),{});auto j=Json::parse(s);Graph g=graph_from_json(j);if(!j.has("name"))g.name=p.stem().string();return g;}
}
