#include "codane/json.hpp"
#include <cctype>
#include <sstream>
namespace codane {
namespace { std::string esc(const std::string&s){std::string o="\"";for(char c:s){if(c=='"'||c=='\\')o+='\\';if(c=='\n')o+='n';else o+=c;}return o+"\"";}
struct Parser{const std::string&s;size_t i=0;void ws(){while(i<s.size()&&std::isspace((unsigned char)s[i]))++i;}char get(){if(i>=s.size())throw std::runtime_error("unexpected end of JSON");return s[i++];}Json value(){ws();if(i>=s.size())throw std::runtime_error("expected value");char c=s[i];if(c=='{')return object();if(c=='[')return array();if(c=='"'){get();std::string x;while(i<s.size()&&s[i]!='"'){if(s[i]=='\\')get();x+=get();}get();return x;}if(s.compare(i,4,"true")==0){i+=4;return true;}if(s.compare(i,5,"false")==0){i+=5;return false;}if(s.compare(i,4,"null")==0){i+=4;return Json();}size_t b=i;while(i<s.size()&&std::string("-+.0123456789eE").find(s[i])!=std::string::npos)++i;return Json(std::stod(s.substr(b,i-b)));}Json object(){get();Json::object o;ws();if(s[i]=='}'){++i;return o;}for(;;){ws();if(get()!='"')throw std::runtime_error("key expected");std::string k;while(s[i]!='"')k+=get();get();ws();if(get()!=':')throw std::runtime_error("colon expected");o[k]=value();ws();char c=get();if(c=='}')return o;if(c!=',')throw std::runtime_error("comma expected");}}Json array(){get();Json::array a;ws();if(s[i]==']'){++i;return a;}for(;;){a.push_back(value());ws();char c=get();if(c==']')return a;if(c!=',')throw std::runtime_error("comma expected");}}};}
std::string Json::dump()const{return std::visit([](auto const&x)->std::string{using T=std::decay_t<decltype(x)>;if constexpr(std::is_same_v<T,std::nullptr_t>)return"null";else if constexpr(std::is_same_v<T,bool>)return x?"true":"false";else if constexpr(std::is_same_v<T,double>){std::ostringstream o;o<<x;return o.str();}else if constexpr(std::is_same_v<T,std::string>)return esc(x);else if constexpr(std::is_same_v<T,array>){std::string o="[";for(auto const&v:x)o+=(o.size()>1?",":"")+v.dump();return o+"]";}else{std::string o="{";for(auto const&[k,v]:x){if(o.size()>1)o+=',';o+=esc(k)+":"+v.dump();}return o+"}";}},v);}
Json Json::parse(const std::string&s){Parser p{s};Json j=p.value();p.ws();if(p.i!=s.size())throw std::runtime_error("trailing JSON");return j;}
}
